apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vm-healthy.yaml
  - vm-progressing-starting.yaml
  - vm-progressing-nostatus.yaml
  - vm-suspended-stopped.yaml
  - vm-suspended-paused.yaml
