apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

namePrefix: pattern1-

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: backend
  team: team-alpha

images:
  - name: backend
    newName: ghcr.io/csz-ghorg/backend
    newTag: latest

