apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-service

namePrefix: pattern1-

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: my-service
  team: team-alpha

images:
  - name: my-service
    newName: ghcr.io/csz-ghorg/my-service
    newTag: latest

