apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

namePrefix: pattern1-

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

replacements:
  - source:
      kind: Service
      name: frontend
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.[].http.paths.[].backend.service.name

commonLabels:
  app: frontend
  team: team-alpha

images:
  - name: frontend
    newName: ghcr.io/csz-ghorg/frontend
    newTag: latest

